name: Deploy Web Infrastructure

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: Provision AWS Infrastructure
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -out=tfplan

    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan

  ansible:
    name: Configure EC2 with Ansible
    runs-on: ubuntu-latest
    needs: terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Run Playbook (Optional)
      run: |
        ansible-playbook -i inventory/aws_ec2.yml playbooks/webserver.yml
      env:
        ANSIBLE_HOST_KEY_CHECKING: False